---
title: "Tips and advice when creating a python software for lab members to use in academia."
subtitle: ""
excerpt: "Here is a talk i gave on PyData Global 2021."
date: 2021-10-29T14:00:00
date_end: "2021-10-29T14:30:00"
show_post_time: false
event: "PyData Global 2021"
event_url: https://pydata.org/global2021
author: "Jeremy Selva"
location: "A Virtual Conference, Anywhere On Earth"
draft: false
# layout options: single, single-sidebar
layout: single
links:
- icon: door-open
  icon_pack: fas
  name: website
  url: https://jauntyjjs.github.io/PyDataGlobal2021Talk
- icon: github
  icon_pack: fab
  name: code
  url: https://github.com/JauntyJJS/PyDataGlobal2021Talk
---

```{r setup, echo=FALSE}
library(xaringanExtra)

knitr::opts_chunk$set(fig.align = "center")

htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clipboard\"></i> Copy Code",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i> Copied!",
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

Stay tuned for video and slides.

```{r, echo=FALSE}

xaringanExtra::embed_xaringan(
  url = "https://jauntyjjs.github.io/PyDataGlobal2021Talk",
  ratio = "16:9"
)

```

